grid: EASE2_N12.5km

datasets:
  full: # mandatory
    name: "ASP_full.parquet"
    save_directory: ./data/intermediate/datasets/EASE2_LARM_N12.5km_v1.1

  train: # mandatory
    name: "ASP_train.parquet"
    save_directory: ./data/intermediate/datasets/EASE2_LARM_N12.5km_v1.1

  test_2020: # optional
    name: "ASP_test_2020-11-01_2020-12-01.parquet"
    save_directory: ./data/intermediate/datasets/EASE2_LARM_N12.5km_v1.1
    split_type: 'periodic'
    period:
      start: '2020-11-01'
      end: '2020-12-01'

  test_2022: # optional
    name: "ASP_test_2022-04-01_2022-05-01.parquet"
    save_directory: ./data/intermediate/datasets/EASE2_LARM_N12.5km_v1.1
    split_type: 'periodic'
    period:
      start: '2022-04-01'
      end: '2022-05-01'
    
  # test_fractional: # optional
  #   name: "ASP_test_fractional.parquet"
  #   save_directory: ./data/intermediate/datasets
  #   split_type: 'fractional'
  #   split_params:
  #     fraction: 0.2
  #     equalization_id: 'primary_id'
    
time_period: 
  start: '2012-08-01'
  end: '2025-10-30'

point_data_sources:
  C2I:
    retracker: 'LARM_smoothed'
    secondary_id:
      2020-2021: 
        id: 2020-2021
        filepath: ./data/raw/C2I_SnowDepths/CRYO2ICE_individul_comparison_BaselineE/2020-2021
      2021-2022: 
        id: 2021-2022
        filepath: ./data/raw/C2I_SnowDepths/CRYO2ICE_individul_comparison_BaselineE/2021-2022
  OIB:
    retracker: None
    secondary_id:
      IDCSI4: 
        id: IDCSI4
        filepath: ./data/raw/OIB_IDCSI4
  AEM_AWI:
    retracker: None
    secondary_id:
      ICEBIRD: 
        id: ICEBIRD
        filepath: ./data/raw/AEM-AWI-ICEBIRD_2019/datasets
      PAMARCMIP: 
        id: PAMARCMIP
        filepath: ./data/raw/AEM-AWI-PAMARCMIP_2017/datasets

CETB:
  directory: ./data/raw/CETB_AMSR2
  channels:
    - 6.9H
    - 6.9V
    - 10.7H
    - 10.7V
    - 18H
    - 18V
    - 23H
    - 23V
    - 36H
    - 36V
    - 89H
    - 89V

ERA5:
  directory: ./data/raw/ERA5_all-param_daily_perMonth_1hourly-sample
  channels:
    - u10
    - v10
    - d2m
    - t2m
    - tp
    - sst
    - skt
    - fal
    - siconc
    - tcwv
    - ssrd
    - strd
    - tclw
    - tciw
    - sf
    - e
    - istl1
    - istl2
    - istl3
    - istl4

derived_ERA5:
  directory: ./data/intermediate/derived_ERA5
  channels: []




