grid: EASE2_N3.125km

output_extent: [-4500000, -4500000, 4500000, 4500000]

ERA5:
  directory: E:/ASP/Data/ERA5_6hourly_pred-param
  channels:
    - siconc

CETB:
  directory: E:/ASP/Data/nsidc-0630_CETB_AMSR2_M_nov-apr
  channels:
    - 6.9H
    - 6.9V
    - 10.7H
    - 10.7V
    - 18H
    - 18V
    - 23H
    - 23V
    - 36H
    - 36V
    - 89H
    - 89V

model_checkpoint: ./data/processed/models/v1.2/ASP_RFR-model_LARM-smoothed_N3.125km.pkl

output:
  directory: ./data/processed/predictions
  name: ASP_snow_depth_predictions_{date}.nc
  chunk_size:
    y: 720
    x: 720

time_period:
  start: 2012-10-31
  end: 2025-05-01

mask:
  channel: siconc
  threshold: 0.75