
# Configuration for splitting the dataset into training and testing sets
input_directory: data/intermediate/datasets
output_directory: data/intermediate/datasets
input_dataset: "ASTD_v1.0-N3.125km-LARM_smoothed.parquet"

# Specify which primary and secondary IDs to include in the split
allowed_primary_ids:
  - C2I
allowed_secondary_ids:
  - 2020-2021
  - 2021-2022

# Define training set configuration
train_set:
    save_file_name: "ASTD_v1.0-train.parquet"

# Define testing set configurations
# Multiple test sets can be defined. Each test set can have its own time period and save file name
test_sets:
    november_2020:
      time_period:
        start: '2020-11-01'
        end: '2020-12-01'
      save_file_name: "ASTD_v1.0-test_nov2020.parquet"

    april_2022:
      time_period:
        start: '2022-04-01'
        end: '2022-05-01'
      save_file_name: "ASTD_v1.0-test_apr2022.parquet"