
EASE2_N25km:
  name: "EASE-Grid 2.0 25km North"
  description: "Equal Area Scalable Earth Grid"
  projection: "Northern Hemisphere, Lambert Azimuthal"
  crs: "EPSG:6931"    
  extent: [-9000000, -9000000, 9000000, 9000000]
  grid_cell_size: [25000,25000]
  rows: 720
  cols: 720

EASE2_S25km:
  name: "EASE-Grid 2.0 25km South"
  description: "Equal Area Scalable Earth Grid"
  projection: "Southern Hemisphere, Lambert Azimuthal"
  crs: "EPSG:6932"
  extent: [-9000000, -9000000, 9000000, 9000000]
  grid_cell_size: [25000,25000]
  rows: 720
  cols: 720

EASE2_N12.5km:
  name: "EASE-Grid 2.0 12.5km North"
  description: "Equal Area Scalable Earth Grid"
  projection: "Northern Hemisphere, Lambert Azimuthal"
  crs: "EPSG:6931"    
  extent: [-9000000, -9000000, 9000000, 9000000]
  grid_cell_size: [12500,12500]
  rows: 1440
  cols: 1440
  
EASE2_S12.5km:
  name: "EASE-Grid 2.0 12.5km South"
  description: "Equal Area Scalable Earth Grid"
  projection: "Southern Hemisphere, Lambert Azimuthal"
  crs: "EPSG:6932"
  extent: [-9000000, -9000000, 9000000, 9000000]
  grid_cell_size: [12500,12500]
  rows: 1440
  cols: 1440

EASE2_N6.25km:
  name: "EASE-Grid 2.0 6.25km North"
  description: "Equal Area Scalable Earth Grid"
  projection: "Northern Hemisphere, Lambert Azimuthal"
  crs: "EPSG:6931"    
  extent: [-9000000, -9000000, 9000000, 9000000]
  grid_cell_size: [6250,6250]
  rows: 2880
  cols: 2880

EASE2_S6.25km:
  name: "EASE-Grid 2.0 6.25km South"
  description: "Equal Area Scalable Earth Grid"
  projection: "Southern Hemisphere, Lambert Azimuthal"
  crs: "EPSG:6932"
  extent: [-9000000, -9000000, 9000000, 9000000]
  grid_cell_size: [6250,6250]
  rows: 2880
  cols: 2880

EASE2_N3.125km:
  name: "EASE-Grid 2.0 3.125km North"
  description: "Equal Area Scalable Earth Grid"
  projection: "Northern Hemisphere, Lambert Azimuthal"
  crs: "EPSG:6931"    
  extent: [-9000000, -9000000, 9000000, 9000000]
  grid_cell_size: [3125,3125]
  rows: 5760
  cols: 5760

EASE2_S3.125km:
  name: "EASE-Grid 2.0 3.125km South"
  description: "Equal Area Scalable Earth Grid"
  projection: "Southern Hemisphere, Lambert Azimuthal"
  crs: "EPSG:6932"
  extent: [-9000000, -9000000, 9000000, 9000000]
  grid_cell_size: [3125,3125]
  rows: 5760
  cols: 5760


ERA5_global:
  name: "ERA5 Global"
  description: "Regular latitude-longitude grid"
  projection: "Geographic"
  crs: "EPSG:4326"
  extent: [-180, -90, 180, 90]
  grid_cell_size: [0.25, 0.25]
  rows: 721
  cols: 1440

ERA5_polar:
  name: "ERA5 with reduced extent"
  description: "Regular latitude-longitude grid"
  projection: "Geographic"
  crs: "EPSG:4326"
  extent: [-180, 45, 180, 90]
  grid_cell_size: [0.25, 0.25]
  rows: 181
  cols: 1440